# Miscelaneous
favicon: /favicon.ico

# fancybox gallery
fancybox: true

# main menu navigation
# ====================================
menu:
  home: /
  archive: /archives
  #category: /categories
  tags: /tags
  about: /about

# site logo introduce and footer quote
# ====================================
logo: Concrete
introduce: "practice makes perfect"
quote: "Some very cool quotes"

# social club
# ====================================
social:
  weibo: 
  github: https://github.com/
  steam:
  linkedin:
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/
  douban:
  tumblr:
  instagram:
  stackoverflow:
  reddit: https://www.reddit.com/user/

# third party services settings
# ===================================

#leanCloud
leancloud:
  app_id:
  app_key:

# comments
# Valine comment system. https://valine.js.org
valine:
  comment_name: 留言板 #your comment area title
  enable: true # if you want use valine, please set this value to true
  app_id:  # your leancloud appId
  app_key:  # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: retro # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 欢迎留言~ O(∩_∩)O # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

#disqus
disqus_shortname: 

mathjax: false
google_analytics: UA-xxxxxxxxx-x
# ==================================
version: 1.0
# ==================================
